[tool.bumpversion]
current_version = "0.1.0"
commit = true
tag = false
message = "Bump version to {new_version}"

[tool.bumpversion.file_patterns]
"VERSION" = [
    {search = "{current_version}", replace = "{new_version}"},
]
"README.md" = [
    {search = "inka-nvim v{current_version}", replace = "inka-nvim v{new_version}"},
]
"lua/inka-nvim/init.lua" = [
    {search = "M.version = '{current_version}'", replace = "M.version = '{new_version}'"},
]

[[tool.bumpversion.files]]
filename = "VERSION"

[[tool.bumpversion.files]]
filename = "lua/inka-nvim/init.lua"